<!DOCTYPE html>
<html lang="<?php echo CHARSET ?>">
<head>
	<meta charset="<?php echo CHARSET ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="robots" content="noindex,nofollow">
	<meta name="generator" content="Maigewan">
	
	<title><?php echo $layout['title'] ?></title>
	
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo HTML_PATH_CORE_IMG.'favicon.png?version='.MAIGEWAN_VERSION ?>">
	
	<!-- Tabler CSS -->
	<link href="<?php echo DOMAIN_ADMIN_THEME_CSS ?>tabler.min.css?version=<?php echo MAIGEWAN_VERSION ?>" rel="stylesheet">
	<link href="<?php echo DOMAIN_ADMIN_THEME_CSS ?>tabler-flags.min.css?version=<?php echo MAIGEWAN_VERSION ?>" rel="stylesheet">
	<link href="<?php echo DOMAIN_ADMIN_THEME_CSS ?>tabler-payments.min.css?version=<?php echo MAIGEWAN_VERSION ?>" rel="stylesheet">
	<link href="<?php echo DOMAIN_ADMIN_THEME_CSS ?>tabler-vendors.min.css?version=<?php echo MAIGEWAN_VERSION ?>" rel="stylesheet">
	
	<!-- Custom CSS -->
	<?php
		echo Theme::cssBootstrapIcons();
		echo Theme::css(array(
			'maigewan.css',
			'maigewan.bootstrap.css'
		), DOMAIN_ADMIN_THEME_CSS);
	?>
	
	<!-- Tabler Theme JS (for dark mode toggle) -->
	<script src="<?php echo DOMAIN_ADMIN_THEME_JS ?>tabler-theme.min.js?version=<?php echo MAIGEWAN_VERSION ?>"></script>
	
	<!-- Core Javascript -->
	<?php
		echo Theme::js(array(
			'maigewan-dom.js',
			'maigewan-datetime.js',
			'maigewan-select.js',
			'maigewan-sortable.js',
			'spa-enhancer.js'
		), DOMAIN_CORE_JS, null);
		echo Theme::js('functions.js', DOMAIN_CORE_JS, null);
	?>
	
	<!-- Plugins -->
	<?php Theme::plugins('adminHead') ?>
	
	<style>
	@media print {
		.no-print {
			display: none !important;
		}
	}
	</style>
</head>

<body>
	<!-- Plugins -->
	<?php Theme::plugins('adminBodyBegin') ?>
	
	<!-- Javascript dynamic generated by PHP -->
	<?php
		echo '<script charset="utf-8">'.PHP_EOL;
		include(PATH_CORE_JS.'variables.php');
		echo '</script>'.PHP_EOL;
	?>
	
	<!-- AJAX utilities -->
	<script src="<?php echo DOMAIN_CORE_JS ?>maigewan-ajax.js?version=<?php echo MAIGEWAN_VERSION ?>"></script>
	
	<!-- Overlay background -->
	<div id="jsshadow" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);z-index:1040;"></div>
	
	<!-- Alert -->
	<?php include('html/alert.php'); ?>
	
	<div class="page">
		<!-- Sidebar - Desktop only -->
		<aside class="navbar navbar-vertical navbar-expand-lg no-print" data-bs-theme="dark">
			<div class="container-fluid">
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-menu" aria-controls="sidebar-menu" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				
				<h1 class="navbar-brand navbar-brand-autodark">
					<a href="<?php echo HTML_PATH_ADMIN_ROOT.'dashboard' ?>">
						<img src="<?php echo HTML_PATH_CORE_IMG ?>logo.svg" width="32" height="32" alt="Maigewan" class="navbar-brand-image">
						<span class="ms-2"><?php echo (defined('MAIGEWAN_PRO'))?'MAIGEWAN PRO':'MAIGEWAN' ?></span>
					</a>
				</h1>
				
				<!-- Mobile navbar actions -->
				<div class="navbar-nav flex-row d-lg-none">
					<div class="nav-item dropdown">
						<a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
							<?php 
								$avatarPath = PATH_UPLOADS_PROFILES.$login->username().'.png';
								if (file_exists($avatarPath)) {
									echo '<span class="avatar avatar-sm" style="background-image: url('.HTML_PATH_UPLOADS_PROFILES.$login->username().'.png)"></span>';
								} else {
									$initial = strtoupper(substr($login->username(), 0, 1));
									echo '<span class="avatar avatar-sm">'.$initial.'</span>';
								}
							?>
						</a>
						<div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
							<a href="<?php echo HTML_PATH_ADMIN_ROOT.'edit-user/'.$login->username() ?>" class="dropdown-item"><?php $L->p('Profile') ?></a>
							<div class="dropdown-divider"></div>
							<a href="<?php echo HTML_PATH_ADMIN_ROOT.'logout' ?>" class="dropdown-item"><?php $L->p('Logout') ?></a>
						</div>
					</div>
				</div>
				
				<!-- Sidebar menu -->
				<div class="collapse navbar-collapse" id="sidebar-menu">
					<?php include('html/sidebar.php'); ?>
				</div>
			</div>
		</aside>
		
		<!-- Navbar - Desktop only -->
		<?php include('html/navbar.php'); ?>
		
		<!-- Page wrapper -->
		<div class="page-wrapper">
			<!-- Page body -->
			<div class="page-body">
				<div class="container-xl">
					<?php
						if (Sanitize::pathFile(PATH_ADMIN_VIEWS, $layout['view'].'.php')) {
							include(PATH_ADMIN_VIEWS.$layout['view'].'.php');
						} elseif ($layout['plugin'] && method_exists($layout['plugin'], 'adminView')) {
							echo $layout['plugin']->adminView();
						} else {
							echo '<div class="empty">';
							echo '<div class="empty-icon"><i class="bi bi-inbox" style="font-size: 3rem;"></i></div>';
							echo '<p class="empty-title">'.$L->g('Page not found').'</p>';
							echo '<p class="empty-subtitle text-secondary">'.$L->g('Choose a page from the sidebar.').'</p>';
							echo '</div>';
						}
					?>
				</div>
			</div>
			
			<!-- Page footer -->
			<footer class="footer footer-transparent d-print-none">
				<div class="container-xl">
					<div class="row text-center align-items-center flex-row-reverse">
						<div class="col-lg-auto ms-lg-auto">
							<ul class="list-inline list-inline-dots mb-0">
								<li class="list-inline-item">
									<a href="https://maigewan.com" target="_blank" class="link-secondary" rel="noopener">
										Maigewan <?php echo MAIGEWAN_VERSION ?>
									</a>
								</li>
							</ul>
						</div>
						<div class="col-12 col-lg-auto mt-3 mt-lg-0">
							<ul class="list-inline list-inline-dots mb-0">
								<li class="list-inline-item">
									&copy; <?php echo date('Y') ?> 
									<a href="." class="link-secondary"><?php echo $site->title() ?></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>
	
	<!-- Tabler Core JS -->
	<script src="<?php echo DOMAIN_ADMIN_THEME_JS ?>tabler.min.js?version=<?php echo MAIGEWAN_VERSION ?>"></script>
	
	<!-- Plugins -->
	<?php Theme::plugins('adminBodyEnd') ?>
</body>
</html>
