<?php defined('MAIGEWAN') or die('Maigewan CMS.'); ?>
{
    "title": "1Dun - 一盾网络安全",
    "slogan": "专业的网络安全服务",
    "description": "1Dun 提供专业的网络安全解决方案,包括安全评估、渗透测试、应急响应等服务",
    "footer": "Copyright © 2025 1Dun.co - All rights reserved",
    "itemsPerPage": 6,
    "theme": "blogx",
    "logo": "",
    "cover": "",
    "image": "",
    "url": "http:\/\/1dun.co",
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "instagram": "",
    "gitlab": "",
    "github": "",
    "linkedin": "",
    "mastodon": "",
    "uriFilters": "page",
    "orderBy": "date",
    "pageNotFound": "",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "dateFormat": "F j, Y",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "markdownParser": true
}
