<?php defined('MAIGEWAN') or die('Maigewan CMS.'); ?>
{
    "currentBuild": 20240806, 
    "title": "I am Guybrush Threepwood, mighty developer", 
    "slogan": "", 
    "description": "", 
    "footer": "I wanna be a pirate!", 
    "itemsPerPage": 6, 
    "language": "zh_CN", 
    "locale": "zh_CN", 
    "timezone": "America/Argentina/Buenos_Aires", 
    "homepage": "welcome", 
    "pageNotFound": "", 
    "uriPage": "/", 
    "uriTag": "/tag/", 
    "uriCategory": "/category/", 
    "uriBlog": "", 
    "url": "http://103.181.135.146", 
    "emailFrom": "", 
    "dateFormat": "F j, Y", 
    "twitter": "", 
    "facebook": "", 
    "codepen": "", 
    "instagram": "", 
    "github": "", 
    "gitlab": "", 
    "linkedin": "", 
    "xing": "", 
    "telegram": "", 
    "mastodon": "", 
    "dribbble": "", 
    "vk": "", 
    "orderBy": "date", 
    "extremeFriendly": true, 
    "autosaveInterval": 2, 
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}", 
    "titleFormatPages": "{{page-title}} | {{site-title}}", 
    "titleFormatCategory": "{{category-name}} | {{site-title}}", 
    "titleFormatTag": "{{tag-name}} | {{site-title}}", 
    "thumbnailWidth": 400, 
    "thumbnailHeight": 400, 
    "thumbnailQuality": 100, 
    "markdownParser": true, 
    "customFields": "[]"
}